  
title: Idéias e Testes
author: marcelokim
email: marcelo.kim2014@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Canto de testes, idéias e análises aleatórias.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  marcelokim # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
