  
title: Idéias, Testes e Curiosidades
author: Marcelo Kim Imai
email: marcelo.kim2014@gmail.com
theme: minima
excerpt_separator: <!--more-->
description: > # this means to ignore newlines until "baseurl:"
  Testes, idéias e análises pessoais.
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  marcelokim # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
  - jekyll-seo-tag
